openapi: 3.0.0
info:
  title: YOLO and OCR Inference API
  description: API for YOLO object detection and OCR text recognition.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local API server

paths:
  /infer/yolo:
    post:
      summary: Perform YOLO object detection
      description: This endpoint accepts an image and returns detected objects along with bounding box coordinates.
      requestBody:
        description: The image to process, either in base64 encoding or as a URL.
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/YoloInferenceRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/YoloInferenceRequest'
      responses:
        '200':
          description: A list of detected objects with their bounding boxes and confidence scores.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YoloInferenceResponse'
        '400':
          description: Bad request, invalid image or missing image.
        '500':
          description: Internal server error.

  /infer/ocr:
    post:
      summary: Perform OCR text recognition
      description: This endpoint accepts an image and returns the extracted text.
      requestBody:
        description: The image to process, either in base64 encoding or as a URL.
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OcrInferenceRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/OcrInferenceRequest'
      responses:
        '200':
          description: The recognized text from the image.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OcrInferenceResponse'
        '400':
          description: Bad request, invalid image or missing image.
        '500':
          description: Internal server error.

components:
  schemas:
    YoloInferenceRequest:
      type: object
      properties:
        image:
          type: string
          description: The image file for inference, either in base64 encoding or as a URL.
          format: byte
    YoloInferenceResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        results:
          type: array
          items:
            $ref: '#/components/schemas/DetectedObject'
    OcrInferenceRequest:
      type: object
      properties:
        image:
          type: string
          description: The image file for OCR processing, either in base64 encoding or as a URL.
          format: byte
    OcrInferenceResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        text:
          type: string
          description: The text extracted from the image.
        details:
          type: array
          items:
            $ref: '#/components/schemas/OcrTextDetail'
    DetectedObject:
      type: object
      properties:
        class:
          type: string
          description: The class of the detected object (e.g., "person", "car").
        confidence:
          type: number
          format: float
          description: Confidence score of the detection.
        bbox:
          type: array
          items:
            type: integer
          description: Bounding box coordinates [x1, y1, x2, y2].
    OcrTextDetail:
      type: object
      properties:
        text:
          type: string
          description: A single word recognized in the image.
        bbox:
          type: array
          items:
            type: integer
          description: Bounding box coordinates for the word [x1, y1, x2, y2].
