# 根日志器: 同时输出到文件和控制台
log4cplus.rootLogger=INFO, DailyRollingFileAppender, ConsoleAppender

# 每日轮转文件 Appender
log4cplus.appender.DailyRollingFileAppender=log4cplus::DailyRollingFileAppender
log4cplus.appender.DailyRollingFileAppender.File=logs/vision-simple.log
log4cplus.appender.DailyRollingFileAppender.Schedule=WEEKLY
log4cplus.appender.DailyRollingFileAppender.MaxBackupIndex=4
log4cplus.appender.DailyRollingFileAppender.layout=log4cplus::PatternLayout
log4cplus.appender.DailyRollingFileAppender.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S} [%c] %-5p - %m%n

# 配置 ConsoleAppender
log4cplus.appender.ConsoleAppender=log4cplus::ConsoleAppender
log4cplus.appender.ConsoleAppender.layout=log4cplus::PatternLayout
log4cplus.appender.ConsoleAppender.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S} [%c] %-5p - %m%n