models:
  - task: "yolo"
    name: "hd2-fp16"
    version: "kV11"
    files:
      model: "assets/hd2-yolo11n-fp16.onnx"
  - task: "yolo"
    name: "hd2-fp32"
    version: "kV11"
    files:
      model: "assets/hd2-yolo11n-fp32.onnx"
  - task: "ocr"
    name: "ppocr-v4"
    version: "kPPOCRv4"
    files:
      det: "assets/ppocr_det.onnx"
      rec: "assets/ppocr_rec.onnx"
      dictionary: "assets/ppocr_keys_v1.txt"
