host: "0.0.0.0"
port: 11451
options:
  static_path: "assets/static"
  infer_framework: "kONNXRUNTIME"
  infer_ep: "kCPU"
  infer_device: "0"
  infer_idle_timeout_ms: "300000"
  infer_sweep_interval_ms: "1000"
  infer_pipeline_capacity: "4"
  infer_pipeline_max_batches: "4"
  infer_max_batch_images: "128"
  infer_timeout_ms: "60000"
  ocr_rec_batch_size: "1"